import argparse
import json
import os
from datetime import datetime
from pathlib import Path

os.environ.setdefault("MPLCONFIGDIR", "/tmp/mplconfig")
os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "2")
Path(os.environ["MPLCONFIGDIR"]).mkdir(parents=True, exist_ok=True)

import tensorflow as tf
from tensorflow.keras import layers, models, optimizers
from tensorflow.keras.applications import VGG16
from tensorflow.keras.callbacks import CSVLogger, EarlyStopping, ModelCheckpoint
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import ImageDataGenerator


PROJECT_ROOT = Path(__file__).resolve().parent
DEFAULT_PREPARED_ROOT = PROJECT_ROOT / "download" / "prepared_normal_mci_ad" / "multiclass"
DEFAULT_OUTPUT_ROOT = PROJECT_ROOT / "download" / "ad_mci_normal"
DEFAULT_CLASSES = ["AD", "MCI", "Normal"]


def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Train task-level VGG16 classifiers for AD/MCI/Normal from the "
            "dataset generated by 07-prepare_normal_mci_ad_dataset.py."
        )
    )
    parser.add_argument(
        "--dataset-root",
        default=os.environ.get("VELORA_TRAIN_DATASET_ROOT", str(DEFAULT_PREPARED_ROOT)),
        help="Path to prepared_dataset/multiclass, or directly to one task directory.",
    )
    parser.add_argument(
        "--output-root",
        default=os.environ.get("VELORA_MODEL_OUTPUT_ROOT", str(DEFAULT_OUTPUT_ROOT)),
    )
    parser.add_argument("--tasks", nargs="*", default=None, help="Task names to train. Omit to train every task.")
    parser.add_argument("--class-names", nargs="+", default=DEFAULT_CLASSES)
    parser.add_argument("--image-size", nargs=2, type=int, default=[100, 100], metavar=("HEIGHT", "WIDTH"))
    parser.add_argument("--batch-size", type=int, default=16)
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--learning-rate", type=float, default=0.0001)
    parser.add_argument("--patience", type=int, default=10)
    parser.add_argument("--weights", choices=["imagenet", "none"], default="imagenet")
    parser.add_argument(
        "--resume",
        action="store_true",
        help="Resume each task from its existing final/best model in the output directory when available.",
    )
    parser.add_argument(
        "--resume-from",
        choices=["final", "best"],
        default="final",
        help="When --resume is used, choose which checkpoint to prefer.",
    )
    parser.add_argument(
        "--initial-model",
        default=None,
        help="Optional .h5 model path to use as the starting point for all requested tasks.",
    )
    parser.add_argument(
        "--fine-tune-from",
        default="block5_conv1",
        help="First VGG16 layer to unfreeze when --weights imagenet is used.",
    )
    parser.add_argument("--steps-per-epoch", type=int, default=None)
    parser.add_argument("--validation-steps", type=int, default=None)
    parser.add_argument("--test-steps", type=int, default=None)
    parser.add_argument("--seed", type=int, default=42)
    return parser.parse_args()


def discover_task_dirs(dataset_root, requested_tasks):
    root = Path(dataset_root)
    if (root / "train").is_dir():
        return [(root.name, root)]

    if requested_tasks:
        return [(task, root / task) for task in requested_tasks]

    task_dirs = sorted(path for path in root.iterdir() if path.is_dir())
    return [(path.name, path) for path in task_dirs]


def validate_task_dir(task_dir, class_names):
    train_dir = task_dir / "train"
    validation_dir = task_dir / "validation"
    test_dir = task_dir / "test"

    if not train_dir.is_dir():
        raise FileNotFoundError(f"Missing train directory: {train_dir}")
    if not validation_dir.is_dir():
        raise FileNotFoundError(f"Missing validation directory: {validation_dir}")

    for split_dir in (train_dir, validation_dir):
        missing = [name for name in class_names if not (split_dir / name).is_dir()]
        if missing:
            raise FileNotFoundError(f"{split_dir} is missing class directories: {missing}")

    return train_dir, validation_dir, test_dir if test_dir.is_dir() else None


def set_vgg_trainable_layers(conv_base, fine_tune_from):
    conv_base.trainable = True
    trainable = False
    for layer in conv_base.layers:
        if layer.name == fine_tune_from:
            trainable = True
        layer.trainable = trainable


def build_model(image_size, class_count, weights, fine_tune_from, learning_rate):
    weights_arg = None if weights == "none" else weights
    conv_base = VGG16(weights=weights_arg, include_top=False, input_shape=(*image_size, 3))

    if weights == "imagenet":
        set_vgg_trainable_layers(conv_base, fine_tune_from)
    else:
        conv_base.trainable = True

    model = models.Sequential(
        [
            conv_base,
            layers.Flatten(name="flatten"),
            layers.Dense(10, activation="relu"),
            layers.Dense(class_count, activation="softmax"),
        ]
    )
    model.compile(
        optimizer=optimizers.Adam(learning_rate=learning_rate),
        loss="categorical_crossentropy",
        metrics=["accuracy"],
    )
    return model


def compile_model(model, learning_rate):
    model.compile(
        optimizer=optimizers.Adam(learning_rate=learning_rate),
        loss="categorical_crossentropy",
        metrics=["accuracy"],
    )
    return model


def select_resume_model(best_model_path, final_model_path, resume_from):
    preferred = final_model_path if resume_from == "final" else best_model_path
    fallback = best_model_path if resume_from == "final" else final_model_path
    if preferred.exists():
        return preferred
    if fallback.exists():
        return fallback
    return None


def make_generators(task_dir, class_names, image_size, batch_size, seed):
    train_dir, validation_dir, test_dir = validate_task_dir(task_dir, class_names)
    datagen = ImageDataGenerator(rescale=1.0 / 255)
    target_size = tuple(image_size)

    train_generator = datagen.flow_from_directory(
        train_dir,
        target_size=target_size,
        batch_size=batch_size,
        class_mode="categorical",
        classes=class_names,
        shuffle=True,
        seed=seed,
    )
    validation_generator = datagen.flow_from_directory(
        validation_dir,
        target_size=target_size,
        batch_size=batch_size,
        class_mode="categorical",
        classes=class_names,
        shuffle=False,
    )

    test_generator = None
    if test_dir is not None:
        missing = [name for name in class_names if not (test_dir / name).is_dir()]
        if missing:
            print(f"warning: {test_dir} is missing class directories {missing}; test evaluation skipped.")
        else:
            test_generator = datagen.flow_from_directory(
                test_dir,
                target_size=target_size,
                batch_size=batch_size,
                class_mode="categorical",
                classes=class_names,
                shuffle=False,
            )

    return train_generator, validation_generator, test_generator


def save_metadata(path, metadata):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(metadata, f, ensure_ascii=False, indent=2)


def load_preprocessing_config(dataset_root):
    root = Path(dataset_root).resolve()
    candidates = [
        root / "preprocessing_config.json",
        root.parent / "preprocessing_config.json",
        root.parent.parent / "preprocessing_config.json",
    ]
    for candidate in candidates:
        if candidate.exists():
            with candidate.open("r", encoding="utf-8") as f:
                config = json.load(f)
            config["path"] = str(candidate)
            return config
    return {}


def train_one_task(task_name, task_dir, args):
    print(f"\n=== task {task_name}: {task_dir} ===")
    image_size = tuple(args.image_size)
    train_generator, validation_generator, test_generator = make_generators(
        task_dir, args.class_names, image_size, args.batch_size, args.seed
    )

    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    task_output = Path(args.output_root) / f"task-{task_name}"
    task_output.mkdir(parents=True, exist_ok=True)
    best_model_path = task_output / f"normal_mci_ad_task-{task_name}_best.h5"
    final_model_path = task_output / f"normal_mci_ad_task-{task_name}_final.h5"
    metadata_path = task_output / f"normal_mci_ad_task-{task_name}_metadata.json"
    log_path = task_output / f"normal_mci_ad_task-{task_name}_{timestamp}.csv"

    loaded_from = None
    if args.initial_model:
        loaded_from = Path(args.initial_model)
    elif args.resume:
        loaded_from = select_resume_model(best_model_path, final_model_path, args.resume_from)

    if loaded_from:
        if not loaded_from.exists():
            raise FileNotFoundError(f"Initial model does not exist: {loaded_from}")
        print(f"loading existing model: {loaded_from}")
        model = load_model(str(loaded_from))
        compile_model(model, args.learning_rate)
    else:
        model = build_model(
            image_size=image_size,
            class_count=len(args.class_names),
            weights=args.weights,
            fine_tune_from=args.fine_tune_from,
            learning_rate=args.learning_rate,
        )

    callbacks = [
        EarlyStopping(monitor="val_accuracy", patience=args.patience, mode="max", restore_best_weights=True),
        ModelCheckpoint(str(best_model_path), monitor="val_accuracy", mode="max", save_best_only=True),
        ModelCheckpoint(str(final_model_path), save_best_only=False),
        CSVLogger(str(log_path)),
    ]

    history = model.fit(
        train_generator,
        steps_per_epoch=args.steps_per_epoch,
        epochs=args.epochs,
        validation_data=validation_generator,
        validation_steps=args.validation_steps,
        callbacks=callbacks,
    )

    model.save(str(final_model_path))
    test_metrics = None
    if test_generator is not None:
        test_loss, test_accuracy = model.evaluate(test_generator, steps=args.test_steps)
        test_metrics = {"loss": float(test_loss), "accuracy": float(test_accuracy)}
        print(f"task {task_name} test_accuracy: {test_accuracy:.4f}")

    metadata = {
        "task": task_name,
        "task_dir": str(task_dir),
        "class_indices": train_generator.class_indices,
        "class_names": args.class_names,
        "image_size": list(image_size),
        "weights": args.weights,
        "fine_tune_from": args.fine_tune_from if args.weights == "imagenet" else None,
        "preprocessing": load_preprocessing_config(args.dataset_root),
        "learning_rate": args.learning_rate,
        "batch_size": args.batch_size,
        "epochs_requested": args.epochs,
        "epochs_trained": len(history.history.get("loss", [])),
        "resumed": bool(loaded_from),
        "loaded_model_path": str(loaded_from) if loaded_from else "",
        "best_model_path": str(best_model_path),
        "final_model_path": str(final_model_path),
        "training_log_path": str(log_path),
        "test_metrics": test_metrics,
    }
    save_metadata(metadata_path, metadata)
    tf.keras.backend.clear_session()
    return metadata


def main():
    args = parse_args()
    tf.keras.utils.set_random_seed(args.seed)

    print(f"dataset_root: {args.dataset_root}")
    print(f"output_root: {args.output_root}")
    print(f"class_names: {args.class_names}")

    task_dirs = discover_task_dirs(args.dataset_root, args.tasks)
    if not task_dirs:
        raise SystemExit(f"No task directories found under {args.dataset_root}")

    results = []
    for task_name, task_dir in task_dirs:
        if not task_dir.exists():
            raise FileNotFoundError(f"Task directory does not exist: {task_dir}")
        results.append(train_one_task(task_name, task_dir, args))

    summary_path = Path(args.output_root) / "training_summary.json"
    save_metadata(summary_path, {"results": results})
    print(f"\nsummary: {summary_path}")


if __name__ == "__main__":
    main()
