name: velora-cognitive-voice
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - ffmpeg
  - libsndfile
  - pip:
<<<<<<< HEAD
      - tensorflow==2.15.1
=======
      - tensorflow[and-cuda]==2.15.1
>>>>>>> origin/main
      - keras==2.15.0
      - numpy==1.26.4
      - h5py==3.16.0
      - fastapi[standard]==0.135.2
      - python-multipart==0.0.22
      - pydub==0.25.1
      - librosa==0.11.0
      - soundfile==0.13.1
      - matplotlib==3.10.8
      - pandas==2.3.3
      - scikit-learn==1.8.0
      - scipy==1.17.1
      - pillow==11.3.0
